lugares = ['Japão', 'Colombia', 'Nova Iorque', 'Maldivas', 'Tóquio' ]
print(lugares)
print (sorted(lugares))
print(lugares)
lugares.reverse()
print(lugares)
lugares.reverse()
print(lugares)
lugares.sort()
print(lugares)
lugares.sort(reverse=True)
print(lugares)
print(len(lugares))
print(f'Quero viajar entre esses {len(lugares)} lugares: {lugares}!')